site_name: Talos Workshop
theme:
  name: terminal
site_url: https://qjoly.github.io/workshop-talos/

nav:
  - Home: "index.md"
  - "What's Kubernetes?": "kubernetes.md"
  - Talos Workshop:
      - "Create your first cluster": "create-first-cluster.md"
      - "Use talhelper to optimize the workflow": "talhelper.md"
      - "Terraform to deploy Talos everywhere": "terraform.md"
      - "Add features by creating extensions": "extensions.md"
